### ISSUE TITLE
isNumber validator

### ISSUE THREAD

**Issue by the-hanalyst** [centripetum/validator#2]
True returns Right(Just(value)) -- success
False returns Left(error) -- failure

**Acceptance Criteria:**
1. Accepts a `Maybe<anything>`
2. Use `isJust` to test that the `Maybe` holds a value
3. If the `isJust` returns false, then the `Maybe` is a `Nothing`:
     1. Use the `createError` utility function to create an error and wrap it in a `Left`: `Left(createError(NOT_A_NUMBER, value))`
3. If `isJust` returns true, then use the following functions to pop the value out of the `Maybe`, wrap it in a `String`, and attempt to parse it to a number:
     1. Use Sanctuary's `maybeToNullable()` to pop the value out of the `Maybe` it's in
     2. Use `String()` to make sure it's a string (for the next step).
     3. Use Sanctuary's `parseFloat()` to parse the string to a number. It will return `Just(number)` if it is a number, and `Nothing` if it is not.
     4. You can use Sanctuary's `pipe` to pipe these together.
4. If the above test returns `Just(number)`, wrap that in a `Right` and return it. That's the value that comes out of the test, not the original value passed into the function (this guarantees the return is a number).
5. If the above test returns `Nothing`, then use the `createError` utility function to create an error and wrap it in a `Left`: `Left(createError(NOT_A_NUMBER, value))` (that is the original value as passed to the validator, not the `Nothing`)

Note: Import NOT_A_NUMBER from `src/errorTypes`. Import `createError` from `src/utilities/createError`. See other validators for examples.

**Comment by walkcoolboy** [comment]
When I was changing the type annotation from String to Number, I did not read the criteria, where it said: "Accept a Maybe<anything>". So what about Just('12')? Should it return Just(12)? if it is expected, we should add another test case.

**Comment by walkcoolboy** [comment]
Another thing I just found: for the definition of type \<Number\> in Sanctuary, Number includes 'NaN'. [https://github.com/sanctuary-js/sanctuary-def/tree/v0.18.1#Number](url)
I just tested it: our process will return Just('NaN') given 'NaN': [https://repl.it/@walkcoolboy/Sanctuary-TypelessNumbergreater-includes-NaN](url)
Should we exclude 'NaN' or not?

**Comment by reubenberghan** [comment]
@walkcoolboy we'd generally want to use these validators to make sure a value is the type we expect so yeah we need to be able to accept any type (in flow this is a `mixed` type).

In the case of `Just('12')` `parseFloat` should give us `Just(12)` so yeah we should have a test case for this.

As for the `NaN` case this is an interesting one. I would say we exclude this as I'm not sure this would be useful in any further validations we might expect to do on a `Number` type or to eventually be stored as data. Though @chasm might have some thoughts...
